#!/bin/bash


#------ sync-labsvault.sh
wget -q https://raw.githubusercontent.com/pvrmza/labsvault/master/scripts/EVE-NG/sync-labsvault -O /tmp/sync-labsvault
if [ $? -eq 0 ]; then
	cp /tmp/sync-labsvault /etc/cron.hourly/90sync_labsvault
	chmod 755 /etc/cron.hourly/90sync_labsvault
fi
#------ update_images.sh
wget -q https://raw.githubusercontent.com/pvrmza/labsvault/master/scripts/EVE-NG/updateimages -O /tmp/update_images
if [ $? -eq 0 ]; then
	cp /tmp/update_images /etc/cron.daily/91update_images
	chmod 755 /etc/cron.daily/91update_images
fi

#------ autoupdate
wget -q https://raw.githubusercontent.com/pvrmza/labsvault/master/scripts/EVE-NG/autoupdate -O /tmp/autoupdate
if [ $? -eq 0 ]; then
	cp /tmp/autoupdate /etc/cron.daily/90auto_update
	chmod 755 /etc/cron.daily/90auto_update
fi
